logLevel: info

rtmp: yes
rtmpAddress: :1935

api: yes
apiAddress: :9997

metrics: yes

hls: yes
hlsAddress: :8888
hlsAllowOrigins:
  - "*"
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 200ms

webrtc: yes
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189
webrtcAllowOrigins:
  - "*"

rtsp: yes
rtspAddress: :8554

paths:
  all:
    source: publisher

authMethod: internal
authInternalUsers:
  - user: admin
    pass: admin
    permissions:
      - action: read
      - action: publish
      - action: api
      - action: metrics
