# Generated by Django 6.0.6 on 2026-06-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_table_alter_eventlogin_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stream_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
