# Generated by Django 6.0.6 on 2026-06-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_recording_link_event_playback_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastsession',
            name='protocol',
        ),
        migrations.AddField(
            model_name='broadcastsession',
            name='playback_url',
            field=models.URLField(default=' ', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broadcastsession',
            name='ingest_url',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='broadcastsession',
            name='stream_key',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
