# Generated by Django 6.0.6 on 2026-06-19 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_sessions_primary(apps, schema_editor):
    BroadcastSession = apps.get_model("events", "BroadcastSession")
    BroadcastSession.objects.update(is_primary=True)


def unmark_existing_sessions_primary(apps, schema_editor):
    BroadcastSession = apps.get_model("events", "BroadcastSession")
    BroadcastSession.objects.update(is_primary=False)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_broadcastsession_protocol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastsession',
            options={'ordering': ['-is_primary', 'id']},
        ),
        migrations.AddField(
            model_name='broadcastsession',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastsession',
            name='name',
            field=models.CharField(default='Camera 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='broadcastsession',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_sessions', to='events.event'),
        ),
        migrations.RunPython(mark_existing_sessions_primary, unmark_existing_sessions_primary),
        migrations.AddConstraint(
            model_name='broadcastsession',
            constraint=models.UniqueConstraint(condition=models.Q(is_primary=True), fields=('event',), name='unique_primary_broadcast_session_per_event'),
        ),
    ]
