# Generated by Django 6.0.6 on 2026-07-03 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_broadcastsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastsession',
            name='allow_viewer_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastsession',
            name='is_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StreamRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('RECORDING', 'Recording'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='RECORDING', max_length=20)),
                ('broadcast_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='events.broadcastsession')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
