# Generated by Django 6.0.6 on 2026-07-07 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_broadcastsession_allow_viewer_recording_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("WHOLE_DAY", "Whole Day (single session per date)"),
                    ("MULTI_SESSION", "Multiple Sessions (custom schedule per date)"),
                ],
                default="WHOLE_DAY",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EventDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("day_number", models.PositiveIntegerField()),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("SESSION", "Session"),
                            ("BREAKFAST_BREAK", "Breakfast Break"),
                            ("TEA_BREAK", "Tea Break"),
                            ("LUNCH_BREAK", "Lunch Break"),
                            ("DINNER_BREAK", "Dinner Break"),
                            ("NETWORKING_BREAK", "Networking Break"),
                            ("CUSTOM_BREAK", "Custom Break"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("track", models.CharField(blank=True, default="main", max_length=100)),
                ("room", models.CharField(blank=True, max_length=100)),
                ("speaker_name", models.CharField(blank=True, max_length=255)),
                ("allow_networking", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="events.eventday",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "track", "order", "start_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="eventday",
            constraint=models.UniqueConstraint(
                fields=("event", "date"), name="unique_event_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventday",
            constraint=models.UniqueConstraint(
                fields=("event", "day_number"), name="unique_event_day_number"
            ),
        ),
    ]
