# Generated by Django 6.0.6 on 2026-07-08 08:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_event_schedule_type_eventday_scheduleitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_overall_rating", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="events.event",
                    ),
                ),
                (
                    "event_date",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="events.eventday",
                    ),
                ),
                (
                    "schedule_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null when is_overall_rating is True.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="events.scheduleitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["schedule_item"], name="events_feed_schedul_a22acc_idx"
                    ),
                    models.Index(
                        fields=["event", "is_overall_rating"],
                        name="events_feed_event_i_53561f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_overall_rating", False)),
                        fields=("schedule_item", "user"),
                        name="one_rating_per_user_per_session",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_overall_rating", True)),
                        fields=("event", "user"),
                        name="one_overall_rating_per_user_per_event",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("is_overall_rating", True),
                                ("schedule_item__isnull", True),
                            ),
                            models.Q(
                                ("is_overall_rating", False),
                                ("schedule_item__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="schedule_item_null_iff_overall",
                    ),
                ],
            },
        ),
    ]
