# Generated by Django 6.0.6 on 2026-07-10 16:24

import django.contrib.postgres.fields
import events.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventday",
            name="allowed_attendance_modes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("PHYSICAL", "Physical (On-site)"),
                        ("VIRTUAL", "Virtual (Online)"),
                        ("HYBRID", "Hybrid"),
                        ("RECORDED", "Recorded Session Only"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=events.constants.default_attendance_modes,
                help_text="Attendance modes users can choose for this event.",
            ),
        ),
    ]
