# Generated by Django 6.0.6 on 2026-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_eventday_allowed_attendance_modes"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allowed_accommodation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="allowed_medical",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="allowed_translation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="allowed_travel",
            field=models.BooleanField(default=True),
        ),
    ]
