# Generated by Django 6.0.6 on 2026-07-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_event_allowed_accommodation_event_allowed_medical_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventday",
            name="unique_event_day_number",
        ),
    ]
