# Generated by Django 6.0.6 on 2026-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_remove_eventday_unique_event_day_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventday",
            name="day_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
