# Generated by Django 6.0.6 on 2026-07-25 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_eventday_day_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="broadcastsession",
            index=models.Index(
                fields=["event", "is_active"], name="events_broa_event_i_db987e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_even_status_5709b6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "scheduled_start"],
                name="events_even_status_95ae2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="events_even_created_fdbe6f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventday",
            index=models.Index(
                fields=["event", "day_number"], name="events_even_event_i_cd9841_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventlogin",
            index=models.Index(
                fields=["event", "logged_in_at"], name="events_even_event_i_f1b493_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventlogin",
            index=models.Index(
                fields=["user", "event"], name="events_even_user_id_f33bad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["user", "event"], name="events_feed_user_id_12c815_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["event", "-created_at"], name="events_feed_event_i_0659bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleitem",
            index=models.Index(
                fields=["day", "track", "order"], name="events_sche_day_id_29b077_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleitem",
            index=models.Index(
                fields=["item_type"], name="events_sche_item_ty_3496e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streamrecording",
            index=models.Index(
                fields=["broadcast_session", "status"],
                name="events_stre_broadca_3602dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="viewersession",
            index=models.Index(
                fields=["event", "left_at"], name="events_view_event_i_4ed4bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="viewersession",
            index=models.Index(
                fields=["user", "event"], name="events_view_user_id_46918b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="viewersession",
            index=models.Index(
                fields=["event", "-joined_at"], name="events_view_event_i_4b3f79_idx"
            ),
        ),
    ]
