# Generated by Django 6.0.6 on 2026-07-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_broadcastsession_events_broa_event_i_db987e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewersession",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="viewersession",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="viewersession",
            name="location_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="viewersession",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.DeleteModel(
            name="EventLogin",
        ),
    ]
