# Generated by Django 6.0.6 on 2026-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_eventlogin_address_eventlogin_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewersession",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
