# Generated by Django 6.0.6 on 2026-08-01 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_viewersession_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="viewersession",
            name="day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viewer_sessions",
                to="events.eventday",
            ),
        ),
        migrations.AddField(
            model_name="viewersession",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viewer_sessions",
                to="events.scheduleitem",
            ),
        ),
        migrations.AddIndex(
            model_name="viewersession",
            index=models.Index(
                fields=["session", "left_at"], name="events_view_session_085bdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="viewersession",
            index=models.Index(
                fields=["day", "left_at"], name="events_view_day_id_243b23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="viewersession",
            index=models.Index(
                fields=["event", "day", "left_at"],
                name="events_view_event_i_11c33a_idx",
            ),
        ),
    ]
