# Generated by Django 6.0.7 on 2026-08-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastsession',
            name='ingest_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='broadcastsession',
            name='playback_url',
            field=models.URLField(),
        ),
    ]
