# Generated by Django 6.0.7 on 2026-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_broadcastsession_ingest_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamrecording',
            name='provider_record_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
