# Generated by Django 6.0.7 on 2026-08-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_broadcastsession_ingest_url_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='streamrecording',
            name='events_stre_broadca_3602dc_idx',
        ),
        migrations.AddField(
            model_name='streamrecording',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='streamrecording',
            name='session',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='events.scheduleitem'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='streamrecording',
            index=models.Index(fields=['status'], name='events_stre_status_8e6785_idx'),
        ),
        migrations.RemoveField(
            model_name='streamrecording',
            name='broadcast_session',
        ),
        migrations.RemoveField(
            model_name='streamrecording',
            name='started_by',
        ),
    ]
