# Generated by Django 6.0.7 on 2026-08-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_streamrecording_events_stre_broadca_3602dc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamrecording',
            name='provider_record_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
