# Generated by Django 6.0.7 on 2026-08-18 06:57

import events.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_chatmessage_reply_to_messagereaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamrecording',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=events.media.recording_upload_path),
        ),
    ]
