# Generated by Django 6.0.6 on 2026-07-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="None", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(default="None", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="motivation",
            field=models.CharField(
                blank=True,
                help_text="What motivates you to attend this event?",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="org_name",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="user",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("ORGANISATION", "Institution or Organisation"),
                    ("INDEPENDENT", "Independent"),
                ],
                default="ORGANISATION",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(default="None", max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
