# Generated by Django 6.0.6 on 2026-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_city_user_designation_user_motivation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(default="+91", max_length=5),
        ),
    ]
