# Generated by Django 6.0.6 on 2026-06-08 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_date', models.CharField(choices=[('21', '21st'), ('22', '22nd')], max_length=10)),
                ('participation_time', models.CharField(choices=[('HALF_DAY', 'Half Day'), ('FULL_DAY', 'Full Day')], max_length=10)),
                ('food_preference', models.CharField(choices=[('VEG', 'Veg'), ('JAIN', 'Jain'), ('VEGAN', 'Vegan'), ('PESCETARIAN', 'Pescetarian'), ('NON_VEG_CHICKEN', 'Non Veg (Chicken only)'), ('NON_VEG_ANY', 'Non Veg (Any)')], max_length=20)),
                ('travel_required', models.BooleanField(default=False)),
                ('travel_arrangement', models.CharField(blank=True, choices=[('FLIGHT_TAXI_HOTEL', 'Flight + Taxi + Hotel'), ('TAXI_HOTEL', 'Taxi + Hotel'), ('HOTEL_ONLY', 'Hotel only'), ('TAXI_ONLY', 'Taxi only'), ('FLIGHT_ONLY', 'Flight only'), ('TRAIN_ONLY', 'Train Only')], max_length=20)),
                ('travel_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('medical_support_required', models.BooleanField(default=False)),
                ('medical_support', models.CharField(blank=True, choices=[('WHEEL_CHAIR', 'Wheel Chair'), ('ATTENDER', 'Attender'), ('BLIND_COMPANION', 'Blind Companion')], max_length=20)),
                ('translation_required', models.BooleanField(default=False)),
                ('translation_language', models.CharField(blank=True, choices=[('KANNADA', 'Kannada'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi')], max_length=20)),
                ('translation_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('HELD', 'Held'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registrations',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
