# Generated by Django 6.0.6 on 2026-06-08 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_table_alter_eventlogin_table'),
        ('registrations', '0002_alter_registration_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='food_preference',
            field=models.CharField(blank=True, choices=[('VEG', 'Veg'), ('JAIN', 'Jain'), ('VEGAN', 'Vegan'), ('PESCETARIAN', 'Pescetarian'), ('NON_VEG_CHICKEN', 'Non Veg (Chicken only)'), ('NON_VEG_ANY', 'Non Veg (Any)'), ('NO_PREFERENCE', 'No Preference')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='medical_support',
            field=models.CharField(blank=True, choices=[('WHEEL_CHAIR', 'Wheel Chair'), ('ATTENDER', 'Attender'), ('BLIND_COMPANION', 'Blind Companion'), ('SIGN_LANGUAGE_INTERPRETER', 'Sign Language Interpreter'), ('HEARING_ASSISTANCE', 'Hearing Assistance'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='participation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='participation_time',
            field=models.CharField(blank=True, choices=[('HALF_DAY', 'Half Day'), ('FULL_DAY', 'Full Day'), ('MULTIPLE_DAYS', 'Multiple Days')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='translation_language',
            field=models.CharField(blank=True, choices=[('HINDI', 'Hindi'), ('ENGLISH', 'English'), ('KANNADA', 'Kannada'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('MARATHI', 'Marathi'), ('GUJARATI', 'Gujarati'), ('BENGALI', 'Bengali'), ('ODIA', 'Odia'), ('ASSAMESE', 'Assamese')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='translation_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='travel_arrangement',
            field=models.CharField(blank=True, choices=[('FLIGHT_TAXI_HOTEL', 'Flight + Taxi + Hotel'), ('TAXI_HOTEL', 'Taxi + Hotel'), ('HOTEL_ONLY', 'Hotel Only'), ('TAXI_ONLY', 'Taxi Only'), ('FLIGHT_ONLY', 'Flight Only'), ('TRAIN_ONLY', 'Train Only'), ('SELF_ARRANGED', 'Self Arranged')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='travel_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_registration'),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='medical_support_required',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='translation_required',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='travel_required',
        ),
    ]
