# Generated by Django 6.0.6 on 2026-06-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_registration_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='participation_date',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='participation_time',
        ),
        migrations.AlterField(
            model_name='registration',
            name='food_preference',
            field=models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('JAIN', 'Jain'), ('VEGAN', 'Vegan'), ('SATVIK', 'Satvik'), ('EGG_VEG', 'Egg Vegetarian'), ('PESCETARIAN', 'Pescetarian'), ('GLUTEN_FREE', 'Gluten Free'), ('LACTOSE_FREE', 'Lactose Free'), ('DIABETIC_FRIENDLY', 'Diabetic Friendly'), ('NUT_ALLERGY', 'Nut Allergy'), ('HALAL', 'Halal'), ('NON_VEG_CHICKEN', 'Non Veg (Chicken Only)'), ('NON_VEG_ANY', 'Non Veg (Any)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='medical_support',
            field=models.CharField(blank=True, choices=[('WHEEL_CHAIR', 'Wheelchair Access'), ('MOBILITY_ASSISTANCE', 'Mobility Assistance'), ('ATTENDER', 'Personal Attender'), ('BLIND_COMPANION', 'Blind Companion / Guide'), ('HEARING_IMPAIRED', 'Hearing Impaired Support'), ('SIGN_LANGUAGE_INTERPRETER', 'Sign Language Interpreter'), ('OXYGEN_SUPPORT', 'Oxygen Support'), ('GUIDE_DOG', 'Guide Dog Accommodation'), ('RESERVED_SEATING', 'Reserved Seating (Medical)'), ('OTHER_MEDICAL', 'Other Medical Requirement')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='translation_language',
            field=models.CharField(blank=True, choices=[('HINDI', 'Hindi'), ('ENGLISH', 'English'), ('KANNADA', 'Kannada'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('BENGALI', 'Bengali'), ('MARATHI', 'Marathi'), ('GUJARATI', 'Gujarati'), ('ODIA', 'Odia'), ('ASSAMESE', 'Assamese'), ('URDU', 'Urdu')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ParticipationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('participation_time', models.CharField(blank=True, choices=[('HALF_DAY', 'Half Day'), ('FULL_DAY', 'Full Day'), ('MULTIPLE_DAYS', 'Multiple Days')], max_length=20, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_dates', to='registrations.registration')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('registration', 'date'), name='unique_registration_date')],
            },
        ),
    ]
