# Generated by Django 6.0.6 on 2026-06-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_remove_registration_participation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participationdate',
            name='participation_time',
        ),
        migrations.AddField(
            model_name='registration',
            name='participation_time',
            field=models.CharField(blank=True, choices=[('HALF_DAY', 'Half Day'), ('FULL_DAY', 'Full Day'), ('MULTIPLE_DAYS', 'Multiple Days')], max_length=20, null=True),
        ),
    ]
