# Generated by Django 6.0.6 on 2026-06-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_remove_participationdate_participation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attendance_mode',
            field=models.CharField(choices=[('PHYSICAL', 'Physical (On-site)'), ('VIRTUAL', 'Virtual (Online)'), ('HYBRID', 'Hybrid'), ('RECORDED', 'Recorded Session Only'), ('UNDECIDED', 'Not Decided Yet')], default='UNDECIDED', max_length=10),
        ),
    ]
