# Generated by Django 6.0.6 on 2026-06-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_registration_attendance_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='food_preference',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='medical_support',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='translation_language',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='translation_status',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='travel_arrangement',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='travel_status',
        ),
        migrations.CreateModel(
            name='RegistrationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_preference', models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('JAIN', 'Jain'), ('VEGAN', 'Vegan'), ('SATVIK', 'Satvik'), ('EGG_VEG', 'Egg Vegetarian'), ('PESCETARIAN', 'Pescetarian'), ('GLUTEN_FREE', 'Gluten Free'), ('LACTOSE_FREE', 'Lactose Free'), ('DIABETIC_FRIENDLY', 'Diabetic Friendly'), ('NUT_ALLERGY', 'Nut Allergy'), ('HALAL', 'Halal'), ('NON_VEG_CHICKEN', 'Non Veg (Chicken Only)'), ('NON_VEG_ANY', 'Non Veg (Any)')], max_length=20, null=True)),
                ('travel_arrangement', models.CharField(blank=True, choices=[('FLIGHT_TAXI_HOTEL', 'Flight + Taxi + Hotel'), ('TAXI_HOTEL', 'Taxi + Hotel'), ('HOTEL_ONLY', 'Hotel Only'), ('TAXI_ONLY', 'Taxi Only'), ('FLIGHT_ONLY', 'Flight Only'), ('TRAIN_ONLY', 'Train Only'), ('SELF_ARRANGED', 'Self Arranged')], max_length=20, null=True)),
                ('travel_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=10, null=True)),
                ('medical_support', models.CharField(blank=True, choices=[('WHEEL_CHAIR', 'Wheelchair Access'), ('MOBILITY_ASSISTANCE', 'Mobility Assistance'), ('ATTENDER', 'Personal Attender'), ('BLIND_COMPANION', 'Blind Companion / Guide'), ('HEARING_IMPAIRED', 'Hearing Impaired Support'), ('SIGN_LANGUAGE_INTERPRETER', 'Sign Language Interpreter'), ('OXYGEN_SUPPORT', 'Oxygen Support'), ('GUIDE_DOG', 'Guide Dog Accommodation'), ('RESERVED_SEATING', 'Reserved Seating (Medical)'), ('OTHER_MEDICAL', 'Other Medical Requirement')], max_length=50, null=True)),
                ('translation_language', models.CharField(blank=True, choices=[('HINDI', 'Hindi'), ('ENGLISH', 'English'), ('KANNADA', 'Kannada'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('BENGALI', 'Bengali'), ('MARATHI', 'Marathi'), ('GUJARATI', 'Gujarati'), ('ODIA', 'Odia'), ('ASSAMESE', 'Assamese'), ('URDU', 'Urdu')], max_length=20, null=True)),
                ('translation_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='registrations.registration')),
            ],
        ),
    ]
