# Generated by Django 6.0.6 on 2026-06-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_remove_registration_food_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetails',
            name='food_preference_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='medical_support_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=10, null=True),
        ),
    ]
