# Generated by Django 6.0.6 on 2026-06-23 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_registrationdetails_food_preference_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='food_preference',
            field=models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('JAIN', 'Jain'), ('VEGAN', 'Vegan'), ('SATVIK', 'Satvik'), ('EGG_VEG', 'Egg Vegetarian'), ('PESCETARIAN', 'Pescetarian'), ('GLUTEN_FREE', 'Gluten Free'), ('LACTOSE_FREE', 'Lactose Free'), ('DIABETIC_FRIENDLY', 'Diabetic Friendly'), ('NUT_ALLERGY', 'Nut Allergy'), ('HALAL', 'Halal'), ('NON_VEG_CHICKEN', 'Non Veg (Chicken Only)'), ('NON_VEG_ANY', 'Non Veg (Any)')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MedicalAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_needs', models.TextField(help_text='e.g. wheelchair accessibility, medications, emergency contact')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_assistance', to='registrations.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('HINDI', 'Hindi'), ('ENGLISH', 'English'), ('KANNADA', 'Kannada'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('BENGALI', 'Bengali'), ('MARATHI', 'Marathi'), ('GUJARATI', 'Gujarati'), ('ODIA', 'Odia'), ('ASSAMESE', 'Assamese'), ('URDU', 'Urdu')], max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation_assistance', to='registrations.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_mode', models.CharField(choices=[('FLIGHT_TAXI_HOTEL', 'Flight + Taxi + Hotel'), ('TAXI_HOTEL', 'Taxi + Hotel'), ('HOTEL_ONLY', 'Hotel Only'), ('TAXI_ONLY', 'Taxi Only'), ('FLIGHT_ONLY', 'Flight Only'), ('TRAIN_ONLY', 'Train Only'), ('SELF_ARRANGED', 'Self Arranged')], max_length=20)),
                ('source_location', models.CharField(blank=True, default='', max_length=255)),
                ('destination_location', models.CharField(blank=True, default='', max_length=255)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_assistance', to='registrations.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RegistrationDetails',
        ),
    ]
