# Generated by Django 6.0.6 on 2026-06-25 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_registration_food_preference_medicalassistance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelassistance',
            name='transport_mode',
            field=models.CharField(choices=[('TAXI', 'Taxi'), ('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('SELF_ARRANGED', 'Self Arranged')], max_length=20),
        ),
        migrations.CreateModel(
            name='AccommodationAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('room_no', models.CharField(blank=True, default='', max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_assistance', to='registrations.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
