# Generated by Django 6.0.6 on 2026-07-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_event_schedule_type_eventday_scheduleitem_and_more"),
        ("registrations", "0010_alter_travelassistance_transport_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["schedule_item__day__date", "schedule_item__start_time"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="participationdate",
            name="unique_registration_date",
        ),
        migrations.AddField(
            model_name="registrationsession",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_registrations",
                to="registrations.registration",
            ),
        ),
        migrations.AddField(
            model_name="registrationsession",
            name="schedule_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_registrations",
                to="events.scheduleitem",
            ),
        ),
        migrations.RemoveField(
            model_name="participationdate",
            name="registration",
        ),
        migrations.AddConstraint(
            model_name="registrationsession",
            constraint=models.UniqueConstraint(
                fields=("registration", "schedule_item"),
                name="unique_registration_session",
            ),
        ),
        migrations.DeleteModel(
            name="ParticipationDate",
        ),
    ]
