# Generated by Django 6.0.6 on 2026-07-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0011_registrationsession_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="participation_time",
        ),
    ]
