# Generated by Django 6.0.6 on 2026-07-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0012_remove_registration_participation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="attendance_mode",
            field=models.CharField(
                choices=[
                    ("PHYSICAL", "Physical (On-site)"),
                    ("VIRTUAL", "Virtual (Online)"),
                    ("HYBRID", "Hybrid"),
                    ("RECORDED", "Recorded Session Only"),
                ],
                default="VIRTUAL",
                max_length=10,
            ),
        ),
    ]
