# Generated by Django 6.0.6 on 2026-07-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0014_remove_registration_attendance_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationsession",
            name="attendance_mode",
        ),
        migrations.AddField(
            model_name="registration",
            name="attendance_mode",
            field=models.CharField(
                choices=[
                    ("PHYSICAL", "Physical (On-site)"),
                    ("VIRTUAL", "Virtual (Online)"),
                    ("HYBRID", "Hybrid"),
                    ("RECORDED", "Recorded Session Only"),
                ],
                default="VIRTUAL",
                max_length=10,
            ),
        ),
    ]
