# Generated by Django 6.0.6 on 2026-07-10 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_feedback"),
        ("registrations", "0015_remove_registrationsession_attendance_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_mode",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Physical (On-site)"),
                            ("VIRTUAL", "Virtual (Online)"),
                            ("HYBRID", "Hybrid"),
                            ("RECORDED", "Recorded Session Only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("HELD", "Held"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={},
        ),
        migrations.AlterModelOptions(
            name="registrationsession",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="registrationsession",
            name="unique_registration_session",
        ),
        migrations.RenameField(
            model_name="registrationsession",
            old_name="registered_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="attendance_mode",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="food_preference",
        ),
        migrations.AddField(
            model_name="registrationsession",
            name="session",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"item_type": "SESSION"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="events.scheduleitem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registrationsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("HELD", "Held"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="registrationsession",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="registrations.registration",
            ),
        ),
        migrations.AlterField(
            model_name="registrationsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("HELD", "Held"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationsession",
            constraint=models.UniqueConstraint(
                fields=("registration", "session"), name="unique_registration_session"
            ),
        ),
        migrations.AddField(
            model_name="registrationday",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_days",
                to="events.eventday",
            ),
        ),
        migrations.AddField(
            model_name="registrationday",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="registrations.registration",
            ),
        ),
        migrations.RemoveField(
            model_name="registrationsession",
            name="schedule_item",
        ),
        migrations.AddConstraint(
            model_name="registrationday",
            constraint=models.UniqueConstraint(
                fields=("registration", "day"), name="unique_registration_day"
            ),
        ),
    ]
