# Generated by Django 6.0.6 on 2026-07-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0016_registrationday_alter_registration_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationday",
            name="status",
        ),
    ]
