# Generated by Django 6.0.6 on 2026-07-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0017_remove_registrationday_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationday",
            name="attendance_mode",
            field=models.CharField(
                choices=[
                    ("PHYSICAL", "Physical (On-site)"),
                    ("VIRTUAL", "Virtual (Online)"),
                    ("HYBRID", "Hybrid"),
                    ("RECORDED", "Recorded Session Only"),
                ],
                default="VIRTUAL",
                max_length=20,
            ),
        ),
    ]
