# Generated by Django 6.0.6 on 2026-07-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0018_alter_registrationday_attendance_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("HOLD", "HOLD"),
                    ("REJECTED", "Rejected"),
                ],
                default="ACCEPTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="registrationsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("HOLD", "HOLD"),
                    ("REJECTED", "Rejected"),
                ],
                default="ACCEPTED",
                max_length=20,
            ),
        ),
    ]
