# Generated by Django 6.0.7 on 2026-08-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_alter_registration_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrationday',
            name='unique_registration_day',
        ),
    ]
