# Generated by Django 6.0.7 on 2026-08-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_alter_registration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationday',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
