# Generated by Django 6.0.7 on 2026-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_broadcastsession_ingest_url_and_more'),
        ('registrations', '0020_remove_registrationday_unique_registration_day'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique_user_event_registration',
        ),
        migrations.AddConstraint(
            model_name='registrationday',
            constraint=models.UniqueConstraint(fields=('registration', 'day'), name='unique_registration_day'),
        ),
    ]
