# Generated by Django 6.0.7 on 2026-08-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0020_registrationday_is_attended'),
        ('registrations', '0021_remove_registration_unique_user_event_registration_and_more'),
    ]

    operations = [
    ]
