# Generated by Django 6.0.7 on 2026-08-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_registration_unique_user_event_registration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique_user_event_registration',
        ),
    ]
