# Generated by Django 6.0.7 on 2026-08-08 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0019_alter_broadcastsession_ingest_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REGISTRATION_CONFIRMED', 'Registration Confirmed'), ('REGISTRATION_STATUS_UPDATE', 'Registration Status Update'), ('ASSISTANCE_STATUS_UPDATE', 'Assistance Status Update'), ('EVENT_REMINDER', 'Event Reminder'), ('BROADCAST_LIVE', 'Broadcast Went Live'), ('GENERAL', 'General Announcement')], max_length=40)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'channel', 'is_read'], name='notificatio_user_id_b4022c_idx')],
            },
        ),
    ]
