# Generated by Django 6.0.7 on 2026-08-14 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_broadcastsession_ingest_url_and_more'),
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event', 'notification_type', 'title'], name='notificatio_event_i_342350_idx'),
        ),
    ]
